# Generated by Django 4.2.1 on 2023-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('gdp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question',models.CharField(max_length=1000)),
                ('firstOption',models.CharField(max_length = 300)),
                ('secondOption',models.CharField(max_length = 300)),
                ('thirdOption',models.CharField(max_length=300, null= True)),
                ('fourthOption',models.CharField(max_length=300, null= True)),
            ],
        )
    ]
