# Generated by Django 4.2.1 on 2023-05-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='League_Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('season', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('league_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.league_season')),
            ],
        ),
    ]
