# Generated by Django 4.2.1 on 2023-05-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_league_season_standing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=50)),
                ('to_currency', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=1)),
                ('rate', models.IntegerField(default=1)),
            ],
        ),
    ]
