# Generated by Django 4.2.1 on 2023-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.CharField(max_length=255)),
            ],
        ),
    ]
