# Generated by Django 4.2.1 on 2023-05-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sportsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
    ]
