# Generated by Django 4.2.1 on 2023-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ipinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Year', models.CharField(max_length=4)),
                ('imdbID', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
            ],
        ),
    ]
